In [2]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras

In [57]:
df = pd.read_csv("CSV_Data_For_3.csv")

In [58]:
df.head(10)

UserID    Order     Time
0  200000000.0  [0,1,0]  [0,0,1]
1  200000000.0  [0,1,0]  [0,0,1]
2  200000000.0  [1,0,0]  [0,1,0]
3  200000000.0  [1,0,0]  [0,0,1]
4  200000000.0  [1,0,0]  [0,0,1]
5  200000000.0  [1,0,0]  [1,0,0]
6  200199695.0  [1,0,0]  [0,1,0]
7  200921635.0  [0,1,0]  [0,1,0]
8  203011533.0  [1,0,0]  [0,0,1]
9  203051353.0  [0,1,0]  [0,0,1]

In [59]:
df.head()

UserID    Order     Time
0  200000000.0  [0,1,0]  [0,0,1]
1  200000000.0  [0,1,0]  [0,0,1]
2  200000000.0  [1,0,0]  [0,1,0]
3  200000000.0  [1,0,0]  [0,0,1]
4  200000000.0  [1,0,0]  [0,0,1]

In [92]:
numpy_data = df.to_numpy()

In [93]:
sample_data = numpy_data[0:-1]
sample_data

array([[200000000.0, '[0,1,0]', '[0,0,1]'],
       [200000000.0, '[0,1,0]', '[0,0,1]'],
       [200000000.0, '[1,0,0]', '[0,1,0]'],
       ...,
       [5670000000000000.0, '[1,0,0]', '[1,0,0]'],
       [5690000000000000.0, '[1,0,0]', '[0,0,1]'],
       [5820000000000000.0, '[1,0,0]', '[0,0,1]']], dtype=object)

In [94]:
for val in sample_data:
    val[1] = np.array(eval(val[1]))
    val[2] = np.array(eval(val[2]))
    print(val[2])

[0 0 1]
[0 0 1]
[0 1 0]
[0 0 1]
[0 0 1]
[1 0 0]
[0 1 0]
[0 1 0]
[0 0 1]
[0 0 1]
[1 0 0]
[0 1 0]
[0 1 0]
[1 0 0]
[1 0 0]
[0 1 0]
[0 1 0]
[0 1 0]
[0 0 1]
[0 0 1]
[0 1 0]
[0 0 1]
[1 0 0]
[1 0 0]
[0 0 1]
[0 0 1]
[1 0 0]
[0 0 1]
[1 0 0]
[0 0 1]
[1 0 0]
[0 0 1]
[1 0 0]
[0 1 0]
[0 0 1]
[0 0 1]
[0 0 1]
[0 0 1]
[0 1 0]
[0 1 0]
[0 0 1]
[0 0 1]
[0 0 1]
[1 0 0]
[0 0 1]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[0 0 1]
[1 0 0]
[0 0 1]
[0 0 1]
[0 0 1]
[0 0 1]
[0 0 1]
[0 0 1]
[0 0 1]
[0 1 0]
[0 0 1]
[0 0 1]
[0 0 1]
[0 0 1]
[0 1 0]
[0 1 0]
[0 1 0]
[0 0 1]
[0 0 1]
[0 0 1]
[0 0 1]
[0 1 0]
[1 0 0]
[0 1 0]
[0 1 0]
[0 0 1]
[1 0 0]
[0 1 0]
[1 0 0]
[0 1 0]
[0 0 1]
[0 0 1]
[0 0 1]
[0 0 1]
[0 1 0]
[1 0 0]
[1 0 0]
[1 0 0]
[0 0 1]
[1 0 0]
[0 0 1]
[0 0 1]
[1 0 0]
[0 1 0]
[1 0 0]
[1 0 0]
[0 1 0]
[0 1 0]
[0 1 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[0 1 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[0 1 0]
[1 0 0]
[1 0 0]
[1 0 0]
[0 0 1]
[1 0 0]
[1 0 0]
[1 0 0]
[0 0 1]
[0 0 1]
[1 0 0]
[0 0 1]
[1 0 0]
[0 1 0]
[1 0 0]
[0 0 1]


[0 1 0]
[0 0 1]
[1 0 0]
[1 0 0]
[0 0 1]
[1 0 0]
[1 0 0]
[0 0 1]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[0 0 1]
[0 0 1]
[1 0 0]
[1 0 0]
[1 0 0]
[0 1 0]
[1 0 0]
[1 0 0]
[0 0 1]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[0 1 0]
[0 0 1]
[0 0 1]
[0 1 0]
[0 1 0]
[0 1 0]
[0 1 0]
[0 1 0]
[0 0 1]
[0 1 0]
[0 1 0]
[0 1 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[0 0 1]
[0 0 1]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[0 0 1]
[0 1 0]
[0 1 0]
[0 0 1]
[0 1 0]
[0 1 0]
[0 0 1]
[1 0 0]
[0 1 0]
[1 0 0]
[1 0 0]
[0 0 1]
[0 1 0]
[0 1 0]
[0 0 1]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[0 0 1]
[1 0 0]
[1 0 0]
[0 1 0]
[0 1 0]
[1 0 0]
[1 0 0]
[1 0 0]
[0 0 1]
[0 0 1]
[0 1 0]
[0 1 0]
[0 0 1]
[1 0 0]
[1 0 0]
[0 0 1]
[1 0 0]
[0 0 1]
[0 0 1]
[1 0 0]
[0 0 1]
[1 0 0]
[1 0 0]
[0 1 0]
[0 1 0]
[0 0 1]
[1 0 0]
[1 0 0]
[0 1 0]
[0 0 1]
[0 0 1]
[0 1 0]
[0 0 1]
[1 0 0]
[1 0 0]
[0 0 1]
[1 0 0]
[0 0 1]
[1 0 0]
[0 1 0]
[1 0 0]
[0 0 1]
[0 1 0]
[1 0 0]
[0 0 1]
[0 0 1]
[1 0 0]
[0 1 0]
[0 0 1]
[0 1 0]
[0 1 0]
[0 0 1]
[0 1 0]


[1 0 0]
[0 0 1]
[1 0 0]
[0 0 1]
[0 0 1]
[0 1 0]
[0 0 1]
[0 0 1]
[1 0 0]
[1 0 0]
[1 0 0]
[0 0 1]
[1 0 0]
[0 1 0]
[0 1 0]
[0 1 0]
[0 1 0]
[1 0 0]
[0 1 0]
[1 0 0]
[0 1 0]
[0 1 0]
[0 1 0]
[0 1 0]
[0 1 0]
[0 1 0]
[0 0 1]
[0 0 1]
[1 0 0]
[1 0 0]
[1 0 0]
[0 1 0]
[0 1 0]
[0 1 0]
[0 1 0]
[0 1 0]
[0 0 1]
[0 0 1]
[0 0 1]
[0 1 0]
[1 0 0]
[1 0 0]
[1 0 0]
[0 1 0]
[0 1 0]
[0 1 0]
[1 0 0]
[1 0 0]
[0 1 0]
[1 0 0]
[0 0 1]
[0 0 1]
[0 0 1]
[1 0 0]
[0 0 1]
[0 1 0]
[0 1 0]
[0 1 0]
[1 0 0]
[0 1 0]
[0 1 0]
[0 0 1]
[0 1 0]
[0 0 1]
[0 1 0]
[0 1 0]
[0 0 1]
[0 1 0]
[0 1 0]
[0 1 0]
[0 1 0]
[0 1 0]
[1 0 0]
[1 0 0]
[0 1 0]
[1 0 0]
[1 0 0]
[0 1 0]
[0 1 0]
[0 1 0]
[1 0 0]
[1 0 0]
[0 1 0]
[0 1 0]
[0 1 0]
[0 1 0]
[0 1 0]
[0 1 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[0 1 0]
[0 0 1]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[0 1 0]
[0 0 1]
[0 1 0]
[0 1 0]
[0 1 0]
[0 1 0]
[1 0 0]
[0 0 1]
[0 0 1]
[1 0 0]
[0 1 0]
[0 1 0]
[0 1 0]
[0 1 0]
[0 1 0]
[1 0 0]
[1 0 0]
[1 0 0]
[0 1 0]
[0 1 0]
[0 1 0]
[0 1 0]


[0 0 1]
[1 0 0]
[1 0 0]
[0 1 0]
[0 0 1]
[0 1 0]
[1 0 0]
[1 0 0]
[1 0 0]
[0 0 1]
[0 0 1]
[0 0 1]
[1 0 0]
[0 1 0]
[1 0 0]
[0 0 1]
[0 0 1]
[0 1 0]
[0 0 1]
[0 0 1]
[0 1 0]
[0 1 0]
[1 0 0]
[1 0 0]
[0 1 0]
[0 1 0]
[0 1 0]
[1 0 0]
[1 0 0]
[1 0 0]
[0 0 1]
[0 0 1]
[1 0 0]
[1 0 0]
[0 0 1]
[0 0 1]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[0 1 0]
[1 0 0]
[0 1 0]
[0 1 0]
[0 1 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[0 0 1]
[0 0 1]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[0 0 1]
[1 0 0]
[0 1 0]
[0 0 1]
[1 0 0]
[0 1 0]
[0 1 0]
[0 1 0]
[0 1 0]
[0 1 0]
[1 0 0]
[1 0 0]
[0 1 0]
[0 0 1]
[0 0 1]
[0 1 0]
[1 0 0]
[1 0 0]
[0 0 1]
[0 1 0]
[0 0 1]
[0 0 1]
[0 0 1]
[0 0 1]
[0 0 1]
[0 1 0]
[0 0 1]
[0 0 1]
[0 0 1]
[0 1 0]
[0 1 0]
[0 0 1]
[0 1 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[0 0 1]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[0 0 1]
[0 0 1]
[0 1 0]
[0 0 1]
[1 0 0]
[0 0 1]
[1 0 0]
[0 1 0]
[0 1 0]
[1 0 0]
[0 0 1]
[1 0 0]
[1 0 0]
[0 0 1]
[0 0 1]
[0 0 1]
[0 1 0]
[0 1 0]
[1 0 0]
[1 0 0]


[0 1 0]
[1 0 0]
[0 1 0]
[0 0 1]
[0 1 0]
[0 1 0]
[0 1 0]
[0 1 0]
[0 1 0]
[0 1 0]
[0 1 0]
[1 0 0]
[1 0 0]
[1 0 0]
[0 0 1]
[0 0 1]
[1 0 0]
[1 0 0]
[1 0 0]
[0 0 1]
[0 0 1]
[0 0 1]
[1 0 0]
[0 1 0]
[0 1 0]
[0 1 0]
[0 1 0]
[0 1 0]
[0 1 0]
[0 1 0]
[0 1 0]
[1 0 0]
[0 1 0]
[0 0 1]
[0 1 0]
[1 0 0]
[1 0 0]
[0 1 0]
[1 0 0]
[0 1 0]
[1 0 0]
[0 0 1]
[0 0 1]
[0 1 0]
[0 1 0]
[0 1 0]
[0 1 0]
[1 0 0]
[1 0 0]
[0 1 0]
[0 1 0]
[1 0 0]
[0 0 1]
[0 0 1]
[0 1 0]
[1 0 0]
[0 0 1]
[1 0 0]
[1 0 0]
[0 1 0]
[0 0 1]
[1 0 0]
[0 0 1]
[0 0 1]
[1 0 0]
[1 0 0]
[0 1 0]
[0 0 1]
[0 1 0]
[0 0 1]
[1 0 0]
[0 0 1]
[0 0 1]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[0 0 1]
[0 0 1]
[1 0 0]
[1 0 0]
[0 1 0]
[1 0 0]
[0 0 1]
[0 1 0]
[1 0 0]
[1 0 0]
[0 1 0]
[1 0 0]
[0 1 0]
[0 1 0]
[0 0 1]
[1 0 0]
[1 0 0]
[0 1 0]
[1 0 0]
[1 0 0]
[1 0 0]
[0 1 0]
[0 1 0]
[0 1 0]
[0 1 0]
[0 1 0]
[0 1 0]
[0 1 0]
[0 1 0]
[1 0 0]
[1 0 0]
[0 1 0]
[0 1 0]
[0 1 0]
[0 0 1]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[0 1 0]
[0 0 1]
[0 1 0]
[1 0 0]
[0 1 0]
[0 1 0]
[1 0 0]
[0 1 0]
[0 1 0]


[0 1 0]
[1 0 0]
[1 0 0]
[1 0 0]
[0 1 0]
[0 0 1]
[0 1 0]
[1 0 0]
[1 0 0]
[1 0 0]
[0 0 1]
[0 1 0]
[1 0 0]
[1 0 0]
[0 1 0]
[1 0 0]
[1 0 0]
[1 0 0]
[0 1 0]
[1 0 0]
[1 0 0]
[1 0 0]
[0 1 0]
[1 0 0]
[1 0 0]
[0 1 0]
[0 1 0]
[0 1 0]
[1 0 0]
[1 0 0]
[1 0 0]
[0 0 1]
[0 0 1]
[0 1 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[0 1 0]
[0 0 1]
[1 0 0]
[1 0 0]
[0 1 0]
[0 0 1]
[0 0 1]
[0 0 1]
[0 1 0]
[0 1 0]
[0 1 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[0 0 1]
[0 1 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[0 1 0]
[0 1 0]
[0 1 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[0 0 1]
[0 1 0]
[0 1 0]
[0 0 1]
[0 0 1]
[0 1 0]
[1 0 0]
[1 0 0]
[1 0 0]
[0 1 0]
[0 1 0]
[0 1 0]
[1 0 0]
[0 1 0]
[1 0 0]
[1 0 0]
[1 0 0]
[0 1 0]
[0 1 0]
[0 0 1]
[1 0 0]
[1 0 0]
[1 0 0]
[0 1 0]
[0 1 0]
[0 1 0]
[0 1 0]
[0 1 0]
[0 1 0]
[0 1 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[0 0 1]
[0 0 1]
[0 1 0]
[0 1 0]
[0 1 0]
[0 1 0]
[1 0 0]
[1 0 0]
[0 1 0]
[0 0 1]
[0 0 1]
[1 0 0]


In [95]:
 # order_food_dict = {uniq: [[order, time], [order, time],   [order, time], [order, time]],   uniq2: [[order, time], [order, time],   [order, time], [order, time]]}

order_food_dict = {}
for sample in sample_data:
    #print(f"Key - {sample[0]}     Value - {' '.join([a for a in sample[1].split()[0:-1]])} {sample[2]}")
    #print("\n")
    key = sample[0]
    values = sample[1:]
    # check if the key is in the dictionary
    if order_food_dict.get(key) is not None:
         #   - get the value for that key
        existing_values = order_food_dict.get(key)
        # append new value to existing values
        existing_values.append(values)
        order_food_dict[key] = existing_values
        pass
    else:
        # create new values array
        new_values = []
        new_values.append(values)
        order_food_dict[key] = new_values
    
   
    pass

In [96]:
WINDOW_SIZE = 1
ORDER_SIZE = 3


new_dummy_data = []

for (k, v) in order_food_dict.items():
    customer_orders = order_food_dict.get(k)
    dummy_data = np.asarray(customer_orders)
    for j in range(len(dummy_data)):
        curr = list(dummy_data[j])
        if j + 1 < len(dummy_data):
            curr.append(dummy_data[j+1][1])
            pass
        else:
            curr.append([0,0,0])

        new_dummy_data.append(curr)
    

In [52]:
# customer_orders = order_food_dict.get(200000000.0)

In [13]:
# customer_orders

In [107]:
# new_dummy_data
x = []
y = []

In [108]:
for i in range(0, len(new_dummy_data)):
    if i + ORDER_SIZE < len(new_dummy_data):
        x.append(new_dummy_data[i : i+ORDER_SIZE])
        y.append(new_dummy_data[i+ORDER_SIZE][1])
        print(f"Inputs -> {new_dummy_data[i : i+ORDER_SIZE]} ::::::: Output -> {new_dummy_data[i+ORDER_SIZE][1]} \n\n")

Inputs -> [[array([0, 1, 0]), array([0, 0, 1]), array([0, 0, 1])], [array([0, 1, 0]), array([0, 0, 1]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 0, 1])]] ::::::: Output -> [0 0 1] 


Inputs -> [[array([0, 1, 0]), array([0, 0, 1]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([0, 0, 1])]] ::::::: Output -> [0 0 1] 


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([0, 0, 1]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), [0, 0, 0]]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([1, 0, 0]), array([0, 0, 1]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), [0, 0, 0]], [array([1, 0, 0]), array([0, 1, 0]), [0, 0, 0]]] ::::::: Ou


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), [0, 0, 0]], [array([0, 1, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), [0, 0, 0]]] ::::::: Output -> [0 0 1] 


Inputs -> [[array([0, 1, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), [0, 0, 0]], [array([1, 0, 0]), array([0, 0, 1]), [0, 0, 0]]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), [0, 0, 0]], [array([1, 0, 0]), array([0, 0, 1]), [0, 0, 0]], [array([1, 0, 0]), array([1, 0, 0]), [0, 0, 0]]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([0, 0, 1]), [0, 0, 0]], [array([1, 0, 0]), array([1, 0, 0]), [0, 0, 0]], [array([0, 1, 0]), array([1, 0, 0]), [0, 0, 0]]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), [0, 0, 0]], [array([0, 1, 0]), array([1, 0, 0]), [0, 0, 0]], [array([1, 0, 0]), array([1, 0, 0]), [0, 0, 0]]] ::::::: Output -> [0 0 1] 


Inputs -> [[array([0, 1, 0]), array([1, 0, 0]), [0


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), [0, 0, 0]], [array([0, 0, 1]), array([1, 0, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), [0, 0, 0]], [array([0, 0, 1]), array([1, 0, 0]), array([1, 0, 0])], [array([0, 0, 1]), array([1, 0, 0]), [0, 0, 0]]] ::::::: Output -> [0 0 1] 


Inputs -> [[array([0, 0, 1]), array([1, 0, 0]), array([1, 0, 0])], [array([0, 0, 1]), array([1, 0, 0]), [0, 0, 0]], [array([1, 0, 0]), array([0, 0, 1]), [0, 0, 0]]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([0, 0, 1]), array([1, 0, 0]), [0, 0, 0]], [array([1, 0, 0]), array([0, 0, 1]), [0, 0, 0]], [array([1, 0, 0]), array([1, 0, 0]), [0, 0, 0]]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([0, 0, 1]), [0, 0, 0]], [array([1, 0, 0]), array([1, 0, 0]), [0, 0, 0]], [array([0, 0, 1]), array([1, 0, 0]), [0, 0, 0]]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array(


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), [0, 0, 0]], [array([1, 0, 0]), array([0, 0, 1]), [0, 0, 0]], [array([1, 0, 0]), array([1, 0, 0]), [0, 0, 0]]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([0, 0, 1]), [0, 0, 0]], [array([1, 0, 0]), array([1, 0, 0]), [0, 0, 0]], [array([1, 0, 0]), array([1, 0, 0]), [0, 0, 0]]] ::::::: Output -> [0 0 1] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), [0, 0, 0]], [array([1, 0, 0]), array([1, 0, 0]), [0, 0, 0]], [array([1, 0, 0]), array([0, 0, 1]), [0, 0, 0]]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), [0, 0, 0]], [array([1, 0, 0]), array([0, 0, 1]), [0, 0, 0]], [array([1, 0, 0]), array([0, 1, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([0, 0, 1]), [0, 0, 0]], [array([1, 0, 0]), array([0, 1, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([0, 1, 


Inputs -> [[array([1, 0, 0]), array([0, 0, 1]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([0, 0, 1])]] ::::::: Output -> [0 0 1] 


Inputs -> [[array([1, 0, 0]), array([0, 0, 1]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([1, 0, 0]), array([0, 0, 1]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 0, 1])]] ::::::: Output -> [0 0 1] 


Inputs -> [[array([1, 0, 0]), array([0, 0, 1]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([


Inputs -> [[array([0, 0, 1]), array([0, 1, 0]), [0, 0, 0]], [array([1, 0, 0]), array([0, 1, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), [0, 0, 0]]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), [0, 0, 0]], [array([1, 0, 0]), array([1, 0, 0]), [0, 0, 0]]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), [0, 0, 0]], [array([1, 0, 0]), array([1, 0, 0]), [0, 0, 0]], [array([1, 0, 0]), array([1, 0, 0]), [0, 0, 0]]] ::::::: Output -> [0 0 1] 


Inputs -


Inputs -> [[array([0, 0, 1]), array([0, 1, 0]), array([1, 0, 0])], [array([0, 0, 1]), array([1, 0, 0]), array([1, 0, 0])], [array([0, 0, 1]), array([1, 0, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([0, 0, 1]), array([1, 0, 0]), array([1, 0, 0])], [array([0, 0, 1]), array([1, 0, 0]), array([1, 0, 0])], [array([0, 0, 1]), array([1, 0, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([0, 0, 1]), array([1, 0, 0]), array([1, 0, 0])], [array([0, 0, 1]), array([1, 0, 0]), array([1, 0, 0])], [array([0, 0, 1]), array([1, 0, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([0, 0, 1]), array([1, 0, 0]), array([1, 0, 0])], [array([0, 0, 1]), array([1, 0, 0]), array([1, 0, 0])], [array([0, 0, 1]), array([1, 0, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([0, 0, 1]), array([1, 0, 0]), array([1, 0, 0])], [array([0, 0, 1]), array([1, 0, 0]), array([1, 0, 0])], [array([0, 0, 1]), array([1, 0, 0]), array([


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([0, 0, 1]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), [0, 0, 0]]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), [0, 0, 0]], [array([1, 0, 0]), array([1, 0, 0]), [0, 0, 0]]] ::::::: Output -> [0 0 1] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), [0, 0, 0]], [array([1, 0, 0]), array([1, 0, 0]), [0, 0, 0]], [array([1, 0, 0]), array([0, 0, 1]), [0, 0, 0]]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), [0, 0, 0]], [array([1, 0, 0]), array([0, 0, 1]), [0, 0, 0]], [array([1, 0, 0]), array([0, 1, 0]), [0, 0, 0]]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), [0, 0, 0]], [array([1, 0, 0]), array([0, 1, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), [0, 0, 0]]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), [0, 0, 0]], [array([0, 0, 1]), array([1, 0, 0]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), [0, 0, 0]], [array([0, 0, 1]), array([1, 0, 0]), array([0, 1, 0])], [array([0, 1, 0]), array([0, 1, 0]), [0, 0, 0]]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([0, 0, 1]), array([1, 0, 0]), array([0, 1, 0])], [array([0, 1, 0]), array([0, 1, 0]), [0, 0, 0]], [array([1, 0, 0]), array([1, 0, 0]), [0, 0, 0]]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([0, 1, 0]), array([0, 1, 0]), [0, 0, 0]], [array([1, 0, 0]), array([1, 0, 0]), [0, 0, 0]], [array([1, 0, 0]), array([0, 1, 0]), [0, 0, 0]]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([1, 0, 0]),


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), [0, 0, 0]]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), [0, 0, 0]], [array([0, 0, 1]), array([1, 0, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), [0, 0, 0]], [array([0, 0, 1]), array([1, 0, 0]), array([1, 0, 0])], [array([0, 0, 1]), array([1, 0, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([0, 0, 1]), array([1, 0, 0]), array([1, 0, 0])], [array([0, 0, 1]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), [0, 0, 0]]] ::::::: Output -

Inputs -> [[array([1, 0, 0]), array([0, 0, 1]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([0, 0, 1])]] ::::::: Output -> [0 0 1] 


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([1, 0, 0]), array([0, 0, 1]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), [0, 0, 0]]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([0, 0, 1]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), [0, 0, 0]], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), [0, 0, 0]], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([0, 1, 0])]] ::::::: Ou


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), [0, 0, 0]], [array([0, 1, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([0, 1, 0]), array([1, 0, 0]), [0, 0, 0]]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([0, 1, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([0, 1, 0]), array([1, 0, 0]), [0, 0, 0]], [array([0, 0, 1]), array([0, 1, 0]), [0, 0, 0]]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([0, 1, 0]), array([1, 0, 0]), [0, 0, 0]], [array([0, 0, 1]), array([0, 1, 0]), [0, 0, 0]], [array([0, 0, 1]), array([0, 1, 0]), [0, 0, 0]]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([0, 0, 1]), array([0, 1, 0]), [0, 0, 0]], [array([0, 0, 1]), array([0, 1, 0]), [0, 0, 0]], [array([1, 0, 0]), array([1, 0, 0]), [0, 0, 0]]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([0, 0, 1]), array([0, 1, 0]), [0, 0, 0]], [array([1, 0, 0]), array([1, 0, 0]), [0, 0, 0]], [array([0, 1, 0]), array([0, 1, 0]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), [0, 0, 0]], [array([1, 0, 0]), array([1, 0, 0]), [0, 0, 0]], [array([0, 1, 0]), array([0, 1, 0]), [0, 0, 0]]] ::::::: Output -> [0 0 1] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), [0, 0, 0]], [array([0, 1, 0]), array([0, 1, 0]), [0, 0, 0]], [array([1, 0, 0]), array([0, 0, 1]), [0, 0, 0]]] ::::::: Output -> [0 0 1] 


Inputs -> [[array([0, 1, 0]), array([0, 1, 0]), [0, 0, 0]], [array([1, 0, 0]), array([0, 0, 1]), [0, 0, 0]], [array([1, 0, 0]), array([0, 0, 1]), [0, 0, 0]]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([1, 0, 0]), array([0, 0, 1]), [0, 0, 0]], [array([1, 0, 0]), array([0, 0, 1]), [0, 0, 0]], [array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([1, 0, 0]), array([0, 0, 1]), [0, 0, 0]], [array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([1, 0, 0]), array([0, 1, 


Inputs -> [[array([0, 1, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), [0, 0, 0]]] ::::::: Output -> [0 0 1] 


Inputs -> [[array([1, 0, 0]), array([0, 0, 1]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), [0, 0, 0]], [array([1, 0, 0]), array([0, 0, 1]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), [0, 0, 0]], [array([1, 0, 0]), array([0, 0, 1]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), [0, 0, 0]]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([1, 0, 0]), array([0, 0, 1]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), [0, 0, 0]], [array([1, 0, 0]), array([0, 1, 0]), [0, 0, 0]]] ::::::: Output -> [1 0 0] 


I


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([1, 0, 0])], [array([0, 1, 0]), array([1, 0, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([0, 0, 1]), array([1, 0, 0])], [array([0, 1, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([0, 1, 0]), array([1, 0, 0]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([0, 1, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([0, 1, 0]), array([1, 0, 0]), array([0, 1, 0])], [array([0, 1, 0]), array([0, 1, 0]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([0, 1, 0]), array([1, 0, 0]), array([0, 1, 0])], [array([0, 1, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([0, 1, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([

Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 0, 1])]] ::::::: Output -> [0 0 1] 


Inputs -> [[array([1, 0, 0]), array([0, 0, 1]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([0, 0, 1]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([0, 0, 1])]] ::::::: Output -> [0 0 1] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([1


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([0, 0, 1]), array([1, 0, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([0, 0, 1]), array([1, 0, 0]), array([1, 0, 0])], [array([0, 0, 1]), array([1, 0, 0]), array([0, 0, 1])]] ::::::: Output -> [0 0 1] 


Inputs -> [[array([0, 0, 1]), array([1, 0, 0]), array([1, 0, 0])], [array([0, 0, 1]), array([1, 0, 0]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([0, 0, 1]), array([1, 0, 0]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([0, 0, 1]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([


Inputs -> [[array([0, 0, 1]), array([0, 1, 0]), array([0, 1, 0])], [array([0, 0, 1]), array([0, 1, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([0, 0, 1]), array([0, 1, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([0, 0, 1]), array([1, 0, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([0, 0, 1]), array([1, 0, 0]), array([1, 0, 0])], [array([0, 1, 0]), array([1, 0, 0]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([0, 0, 1]), array([1, 0, 0]), array([1, 0, 0])], [array([0, 1, 0]), array([1, 0, 0]), array([0, 1, 0])], [array([0, 0, 1]), array([0, 1, 0]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([0, 1, 0]), array([1, 0, 0]), array([0, 1, 0])], [array([0, 0, 1]), array([0, 1, 0]), array([0, 1, 0])], [array([0, 0, 1]), array([0, 1, 0]), array([


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([1, 0, 0])], [array([0, 1, 0]), array([1, 0, 0]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), array([1, 0, 0])], [array([0, 1, 0]), array([1, 0, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([0, 1, 0]), array([1, 0, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([1, 0, 0])], [array([0, 0, 1]), array([1, 0, 0]), array([0, 0, 1])]] ::::::: Output -> [0 0 1] 


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), array([1, 0, 0])], [array([0, 0, 1]), array([1, 0, 0]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([0, 0, 1])], [array([0, 0, 1]), array([0, 0, 1]), array([0, 0, 1])], [array([0, 0, 1]), array([0, 0, 1]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([0, 0, 1]), array([0, 0, 1]), array([0, 0, 1])], [array([0, 0, 1]), array([0, 0, 1]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 0, 1])]] ::::::: Output -> [0 0 1] 


Inputs -> [[array([0, 0, 1]), array([0, 0, 1]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([0, 0, 1])]] ::::::: Output -> [0 0 1] 


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([0, 0, 1])], [array([0, 1, 0]), array([0, 0, 1]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([0, 0, 1]), array([0, 0, 1])], [array([0, 1, 0]), array([0, 0, 1]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([0, 1, 0]), array([1, 0, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([0, 1, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([0, 0, 1])]] ::::::: Output -> [0 0 1] 


Inputs -> [[array([0, 1, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([0, 0, 1])], [array([0, 1, 0]), array([0, 0, 1]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([0, 0, 1])], [array([0, 1, 0]), array([0, 0, 1]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 0, 1])], [array([0, 0, 1]), array([0, 0, 1]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), array([0, 0, 1])], [array([0, 0, 1]), array([0, 0, 1]), array([0, 1, 0])], [array([0, 1, 0]), array([0, 1, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([0, 0, 1]), array([0, 0, 1]), array([0, 1, 0])], [array([0, 1, 0]), array([0, 1, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([0, 1, 0]), array([0, 1, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([


Inputs -> [[array([0, 0, 1]), array([0, 1, 0]), array([0, 1, 0])], [array([0, 0, 1]), array([0, 1, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([0, 0, 1]), array([0, 1, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([


Inputs -> [[array([1, 0, 0]), array([0, 0, 1]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 0, 1])]] ::::::: Output -> [0 0 1] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([0, 0, 1])]] ::::::: Output -> [0 0 1] 


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([1, 0, 0]), array([0, 0, 1]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([1, 0, 0]), array([0, 0, 1]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([0, 1, 0]), array([0, 1, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([0, 1, 0]), array([0, 1, 0]), array([1, 0, 0])], [array([0, 1, 0]), array([1, 0, 0]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([0, 1, 0]), array([0, 1, 0]), array([1, 0, 0])], [array([0, 1, 0]), array([1, 0, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([


Inputs -> [[array([0, 0, 1]), array([0, 1, 0]), array([0, 0, 1])], [array([0, 0, 1]), array([0, 0, 1]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([0, 0, 1]), array([0, 0, 1]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([


Inputs -> [[array([1, 0, 0]), array([0, 0, 1]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([


Inputs -> [[array([0, 0, 1]), array([0, 0, 1]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([0, 1, 0]), array([0, 1, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([0, 1, 0]), array([0, 1, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([0, 0, 1])]] ::::::: Output -> [0 0 1] 


Inputs -> [[array([0, 1, 0]), array([0, 1, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([0, 0, 1])]] ::::::: Output -> [0 0 1] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([0, 0, 1])]] ::::::: Output -> [0 0 1] 


Inputs -> [[array([1, 0, 0]), array([0, 0, 1]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([


Inputs -> [[array([0, 0, 1]), array([1, 0, 0]), array([0, 1, 0])], [array([0, 0, 1]), array([0, 1, 0]), array([0, 1, 0])], [array([0, 1, 0]), array([0, 1, 0]), array([0, 0, 1])]] ::::::: Output -> [0 0 1] 


Inputs -> [[array([0, 0, 1]), array([0, 1, 0]), array([0, 1, 0])], [array([0, 1, 0]), array([0, 1, 0]), array([0, 0, 1])], [array([0, 1, 0]), array([0, 0, 1]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([0, 1, 0]), array([0, 1, 0]), array([0, 0, 1])], [array([0, 1, 0]), array([0, 0, 1]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([0, 0, 1])]] ::::::: Output -> [0 0 1] 


Inputs -> [[array([0, 1, 0]), array([0, 0, 1]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([

Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([0, 1, 0])], [array([0, 0, 1]), array([0, 1, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([0, 0, 1]), array([0, 1, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([0, 1, 0])], [array([0, 1, 0]), array([0, 1, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([0, 1, 0])], [array([0, 1, 0]), array([0, 1, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([0, 1, 0]), array([0, 1, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([


Inputs -> [[array([1, 0, 0]), array([0, 0, 1]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([


Inputs -> [[array([0, 1, 0]), array([1, 0, 0]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([0, 0, 1]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([0, 0, 1]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), array([0, 0, 1])], [array([0, 0, 1]), array([0, 0, 1]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([0, 0, 1]), array([0, 0, 1]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([0, 1, 0])], [array([0, 0, 1]), array([0, 1, 0]), array([


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([0, 1, 0]), array([1, 0, 0]), array([0, 0, 1])]] ::::::: Output -> [0 0 1] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([0, 1, 0]), array([1, 0, 0]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([0, 1, 0]), array([1, 0, 0]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([1, 0, 0])], [array([0, 1, 0]), array([1, 0, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([0, 0, 1]), array([1, 0, 0])], [array([0, 1, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([0, 1, 0]), array([1, 0, 0]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([0, 1, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([0, 1, 0]), array([1, 0, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([


Inputs -> [[array([0, 0, 1]), array([1, 0, 0]), array([0, 1, 0])], [array([0, 1, 0]), array([0, 1, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([0, 1, 0]), array([0, 1, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([0, 1, 0])], [array([0, 1, 0]), array([0, 1, 0]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([0, 1, 0])], [array([0, 1, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([0, 1, 0]), array([0, 1, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([0, 1, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([0, 1, 0]), array([0, 1, 0]), array([1, 0, 0])], [array([0, 1, 0]), array([1, 0, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([0, 1, 0]), array([0, 1, 0]), array([1, 0, 0])], [array([0, 1, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([0, 1, 0]), array([1, 0, 0]), array([


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([0, 0, 1]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([0, 1, 0]), array([1, 0, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([0, 1, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([0, 1, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([0, 1, 0]), array([0, 1, 0]), array([0, 0, 1])]] ::::::: Output -> [0 0 1] 


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([0, 1, 0]), array([0, 1, 0]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([0, 1, 0]), array([0, 1, 0]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([1, 0, 0]), array([0, 0, 1]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([1, 0, 0])], [array([0, 0, 1]), array([1, 0, 0]), array([


Inputs -> [[array([1, 0, 0]), array([0, 0, 1]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([0, 1, 0]), array([1, 0, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([0, 1, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([0, 1, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([0, 1, 0])], [array([0, 1, 0]), array([0, 1, 0]), array([0, 0, 1])]] ::::::: Output -> [0 0 1] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([0, 1, 0])], [array([0, 1, 0]), array([0, 1, 0]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([0, 1, 0])], [array([0, 1, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([0, 1, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([0, 1, 0]), array([1, 0, 0]), array([0, 0, 1])]] ::::::: Output -> [0 0 1] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([0, 1, 0]), array([1, 0, 0]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([0, 0, 1])]] ::::::: Output -> [0 0 1] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([0, 0, 1])], [array([0, 0, 1]), array([0, 0, 1]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([0, 0, 1])], [array([0, 0, 1]), array([0, 0, 1]), array([1, 0, 0])], [array([0, 1, 0]), array([1, 0, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([0, 0, 1]), array([0, 0, 1]), array([1, 0, 0])], [array([0, 1, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([0, 1, 0]), array([1, 0, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([0, 1, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([0, 1, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([0, 0, 1]), array([1, 0, 0]), array([

Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([0, 1, 0]), array([1, 0, 0]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([0, 1, 0]), array([1, 0, 0]), array([0, 1, 0])], [array([0, 1, 0]), array([0, 1, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([0, 1, 0]), array([1, 0, 0]), array([0, 1, 0])], [array([0, 1, 0]), array([0, 1, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([0, 1, 0]), array([0, 1, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1


Inputs -> [[array([0, 0, 1]), array([0, 0, 1]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([0, 0, 1])]] ::::::: Output -> [0 0 1] 


Inputs -> [[array([1, 0, 0]), array([0, 0, 1]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), [0, 0, 0]]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([1, 0, 0]), array([0, 0, 1]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), [0, 0, 0]], [array([1, 0, 0]), array([0, 1, 0]), [0, 0, 0]]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([0, 0, 1]), [0, 0, 0]], [array([1, 0, 0]), array([0, 1, 0]), [0, 0, 0]], [array([0, 1, 0]), array([1, 0, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), [0, 0, 0]], [array([0, 1, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), [0, 0, 0]]] ::::::: Output -> [0 1 0] 


Inputs -


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([0, 0, 1])], [array([0, 0, 1]), array([0, 0, 1]), array([0, 0, 1])]] ::::::: Output -> [0 0 1] 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([0, 0, 1])], [array([0, 0, 1]), array([0, 0, 1]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([0, 0, 1])]] ::::::: Output -> [0 0 1] 


Inputs -> [[array([0, 0, 1]), array([0, 0, 1]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([0, 0, 1]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([0, 0, 1]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), [0, 0, 


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([1, 0, 0])], [array([0, 0, 1]), array([1, 0, 0]), array([0, 0, 1])]] ::::::: Output -> [0 0 1] 


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), array([1, 0, 0])], [array([0, 0, 1]), array([1, 0, 0]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([0, 0, 1])]] ::::::: Output -> [0 0 1] 


Inputs -> [[array([0, 0, 1]), array([1, 0, 0]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([0, 0, 1])], [array([0, 0, 1]), array([0, 0, 1]), array([1, 0, 0])]] ::::::: Output -> [1 0 0] 


Inputs -> [[array([1, 0, 0]), array([0, 0, 1]), array([0, 0, 1])], [array([0, 0, 1]), array([0, 0, 1]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), [0, 0, 0]]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([0, 0, 1]), array([0, 0, 1]), array([1, 0, 0])], [array([1, 0, 0]), array([1, 0, 0]), [0, 0, 0]], [array([0, 0, 1]), array([0, 1, 0]), array([0, 0, 1])]] ::


Inputs -> [[array([1, 0, 0]), array([1, 0, 0]), [0, 0, 0]], [array([1, 0, 0]), array([0, 1, 0]), [0, 0, 0]], [array([1, 0, 0]), array([0, 1, 0]), array([0, 0, 1])]] ::::::: Output -> [0 0 1] 


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), [0, 0, 0]], [array([1, 0, 0]), array([0, 1, 0]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), array([0, 0, 1])], [array([1, 0, 0]), array([0, 0, 1]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([1, 0, 0]), array([0, 0, 1]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([0, 1, 0]), array([0, 1, 0]), array([0, 1, 0])]] ::::::: Output -> [0 1 0] 


Inputs -> [[array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([0, 1, 0]), array([0, 1, 0]), array([0, 1, 0])], [array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0])]] ::::::: O

In [110]:
x_train= np.array(x)
y_train = np.array(y)

array([0, 1, 0])

In [53]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Reshape,LSTM,Dropout,Activation

In [127]:
model = Sequential()
model.add(Dense(256, input_shape=(3,3,3),activation = 'softmax'))
model.add(Reshape((3,256*3)))
model.add(LSTM(10,return_sequences=True))
model.add(LSTM(10))
model.add(Dense(3))
model.add(Dropout(0.2))

In [119]:
model.summary()

Model: "sequential_15"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_22 (Dense)             (None, 3, 3, 256)         1024      
_________________________________________________________________
reshape_12 (Reshape)         (None, 3, 768)            0         
_________________________________________________________________
lstm_16 (LSTM)               (None, 3, 10)             31160     
_________________________________________________________________
lstm_17 (LSTM)               (None, 10)                840       
_________________________________________________________________
dense_23 (Dense)             (None, 3)                 33        
_________________________________________________________________
dropout_8 (Dropout)          (None, 3)                 0         
Total params: 33,057
Trainable params: 33,057
Non-trainable params: 0
_________________________________________________

In [128]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['acc'])

In [129]:
model.fit(x_train,y_train,epochs=20,batch_size=2,validation_split=0.2)

Epoch 1/20
3261/3261 [==============================] - 15s 5ms/step - loss: nan - acc: 0.4468 - val_loss: nan - val_acc: 0.4243
Epoch 2/20
3261/3261 [==============================] - 14s 4ms/step - loss: nan - acc: 0.4466 - val_loss: nan - val_acc: 0.4243
Epoch 3/20
3261/3261 [==============================] - 15s 5ms/step - loss: nan - acc: 0.4466 - val_loss: nan - val_acc: 0.4243
Epoch 4/20
3261/3261 [==============================] - 14s 4ms/step - loss: nan - acc: 0.4466 - val_loss: nan - val_acc: 0.4243
Epoch 5/20
3261/3261 [==============================] - 13s 4ms/step - loss: nan - acc: 0.4466 - val_loss: nan - val_acc: 0.4243
Epoch 6/20
3261/3261 [==============================] - 13s 4ms/step - loss: nan - acc: 0.4466 - val_loss: nan - val_acc: 0.4243
Epoch 7/20
3261/3261 [==============================] - 13s 4ms/step - loss: nan - acc: 0.4466 - val_loss: nan - val_acc: 0.4243
Epoch 8/20
3261/3261 [==============================] - 13s 4ms/step - loss: nan - acc: 0.4466 - 

In [85]:
model.output_shape

(None, 3)

In [111]:
model = keras.Sequential()
model.add(keras.layers.Dense(64, input_shape=(3,3,3)))
model.add(keras.layers.Reshape((3, 64 * 3)))
model.add(tf.keras.layers.LSTM(4, return_sequences=True))
model.add(tf.keras.layers.LSTM(4))
model.add(tf.keras.layers.Dense(3))
model.add(tf.keras.layers.Dropout(0.2))
model.add(keras.layers.Activation('softmax'))

In [20]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=["acc"])

In [51]:
np.array(new_dummy_data).shape

(8156, 3, 3)

In [21]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 3, 3, 64)          256       
_________________________________________________________________
reshape (Reshape)            (None, 3, 192)            0         
_________________________________________________________________
lstm (LSTM)                  (None, 3, 4)              3152      
_________________________________________________________________
lstm_1 (LSTM)                (None, 4)                 144       
_________________________________________________________________
dense_1 (Dense)              (None, 3)                 15        
_________________________________________________________________
dropout (Dropout)            (None, 3)                 0         
_________________________________________________________________
activation (Activation)      (None, 3)                 0

In [22]:
np.array(y).shape

(7, 3)

In [23]:
model.fit(x, y, epochs=10, batch_size=2, validation_split=0.2) 

Epoch 1/10
3/3 [==============================] - 2s 761ms/step - loss: 1.0761 - acc: 0.6000 - val_loss: 1.0942 - val_acc: 0.5000
Epoch 2/10
3/3 [==============================] - 0s 27ms/step - loss: 1.0470 - acc: 0.8000 - val_loss: 1.0879 - val_acc: 0.5000
Epoch 3/10
3/3 [==============================] - 0s 19ms/step - loss: 1.0264 - acc: 0.8000 - val_loss: 1.0825 - val_acc: 0.5000
Epoch 4/10
3/3 [==============================] - 0s 10ms/step - loss: 1.0167 - acc: 0.8000 - val_loss: 1.0766 - val_acc: 0.5000
Epoch 5/10
3/3 [==============================] - 0s 11ms/step - loss: 1.0160 - acc: 0.8000 - val_loss: 1.0701 - val_acc: 0.5000
Epoch 6/10
3/3 [==============================] - 0s 10ms/step - loss: 0.9768 - acc: 0.8000 - val_loss: 1.0639 - val_acc: 0.5000
Epoch 7/10
3/3 [==============================] - 0s 10ms/step - loss: 0.9572 - acc: 0.8000 - val_loss: 1.0573 - val_acc: 0.5000
Epoch 8/10
3/3 [==============================] - 0s 10ms/step - loss: 0.9284 - acc: 0.8000 - va

In [235]:
model.save("model.h5")